# Built with Jekyll 3.2.0

# Setup
title:               "The Theory of Conceptual Labor"
tagline:             'I GUESS I NEED A TAGLINE'
description:         'Conceptual Labor is a theory of ways that one must work when the job one is doing cannot be easily explained or understood. This website contains the full text of the Theory, a bibliography, and a blog.'
url:                 'http://conceptuallabor.com/'
baseurl:             ''

# About/contact
author:
  name:              'Ním Wunnan'
  url:               'https://wunnan.com'
  email:             'nim@wunnan.com'

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true
  bibliography:
    output: true
  blog:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."

#Custom
draft: 1


