# Built with Jekyll 3.2.0

# Setup
title:               "The Theory of Conceptual Labor"
tagline:             ''
description:         'Conceptual labor is the experience of doing work that redefines itself as you do it.'
url:                 'https://conceptuallabor.com/'
baseurl:             ''

# About/contact
author:
  name:              'Ním Daghlian'
  url:               'http://nimdaghlian.com'
  email:             'nimdaghlian@gmail.com'

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true
  bibliography:
    output: false
  blog:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - utility
# Theme
theme: "ed."

#Custom
draft: 2
